# Generated by Django 6.0.5 on 2026-05-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='especialidade',
            field=models.CharField(choices=[('Otorrinolaringologista', 'Otorrinolaringologista'), ('Fonoaudiólogo', 'Fonoaudiólogo')], default='Fonoaudiólogo', max_length=100),
        ),
    ]
