# Generated by Django 6.0.5 on 2026-05-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0002_paciente_email_alter_profissional_especialidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
