# Generated by Django 6.0.5 on 2026-05-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0003_profissional_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
