# Generated by Django 6.0.5 on 2026-05-08 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0004_alter_consulta_observacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateTimeField(auto_now_add=True)),
                ('anamnese', models.CharField()),
                ('conduta', models.TextField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField()),
                ('avaliacao_vocal', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='logica.paciente')),
            ],
        ),
    ]
