# Generated by Django 4.2.30 on 2026-05-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logica", "0005_registroconsulta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroconsulta",
            name="anamnese",
            field=models.TextField(),
        ),
    ]
