# Generated by Django 4.2.30 on 2026-05-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logica", "0007_paciente_status_exclusao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paciente",
            name="status_exclusao",
        ),
    ]
