# Generated by Django 4.2.30 on 2026-05-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logica", "0008_remove_paciente_status_exclusao"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="status_exclusao",
            field=models.CharField(
                choices=[
                    ("ATIVO", "Ativo"),
                    ("PENDENTE", "Pendente"),
                    ("EXCLUIDO", "EXCLUIDO"),
                ],
                default="ATIVO",
                max_length=20,
            ),
        ),
    ]
