# Generated by Django 5.2.15 on 2026-06-27 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0010_profissional_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroconsulta',
            name='consulta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logica.consulta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroconsulta',
            name='profissional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logica.profissional'),
            preserve_default=False,
        ),
    ]
