# Generated by Django 5.2.15 on 2026-06-27 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0011_registroconsulta_consulta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroconsulta',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logica.consulta'),
        ),
    ]
